### ISSUE TITLE
Support for visual voicemail

### ISSUE THREAD

**Issue by rocket2nfinity** [ubports/dialer-app#130]
Visual Voicemail is a carrier feature that transcribes your voicemail messages and automatically displays them as text, so you don't have to call your mailbox to know who called and what they want. It works by sending VVM messages to the phone.  UT Messaging app receives these codes, but does not know what to do with them. Requesting VVM support to translate those messages, so Messaging app displays the actual message instead of the code.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/130

Sorry for your inconvenience.
