### ISSUE TITLE
[Suggestion For Improvement] Incoming call screen

### ISSUE THREAD

**Issue by codinghedgehog-python** [ubports/dialer-app#133]
As it is now the user is notified about incoming call by a little rectangle-ish popup towards the top of the screen which
makes perfect sense if you're browsing through your phone.

However, if the phone is locked and not being used it would be great to have incoming call fill up the entire screen with
a picture (if saved) of the caller, otherwise just use a template picture.

This change would really add to the beauty of Ubuntu Touch phone in my honest opinion.

**Comment by lduboeuf** [comment]
need mockup first

**Comment by codinghedgehog-python** [comment]
> need mockup first

I'd imagine something like this:

https://www.dropbox.com/s/ushx1v5q4kkqzfk/imageedit_9_8145972192.gif?raw=1

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/133

Sorry for your inconvenience.
