### ISSUE TITLE
reminder: protect pendingLiveCall 

### ISSUE THREAD

**Issue by lduboeuf** [ubports/dialer-app#144]
what if telepathy never ready ?
https://github.com/ubports/dialer-app/blob/xenial/src/qml/dialer-app.qml#L110

Should be doable with a Timer to reset the property

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/144

Sorry for your inconvenience.
