### ISSUE TITLE
Prefix matching of contacts

### ISSUE THREAD

**Issue by greskom** [ubports/dialer-app#170]
Hello,

I have a feature request on prefix matching of contacts in dial application. I would like to store the corporate prefix into one contact ie. Company with number ie. +421 2 111 11. When some extension from the corporation calls me, I would like to see not the full number +421 2 111 11 111 dialling. But the contact match to be done. I would like to see: Company:111 is calling. Would that be possible?

Thanks

Marek

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/170

Sorry for your inconvenience.
