### ISSUE TITLE
Unable to mute call

### ISSUE THREAD

**Issue by joelselvaraj** [ubports/dialer-app#171]
There is a mute/mic icon present during an ongoing call. 

**Expected Behaviour**
It mutes the call when we press the mic icon.
<img src="https://user-images.githubusercontent.com/12579216/130017416-57c9ef89-84ed-4d2b-9dfb-9bd5e8baef6b.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/12579216/130017819-7980530d-f9d5-49e1-a5c7-c2e117418f8a.png" width="200" height="400" />

**What's Happening**
The audio is still audible on the other end even if the mic shows like its disabled. 

I am not particularly sure if its a halium9/even older halium issue or specific to my device (Poco F1). It would nice if someone can confirm this issue exist.

**Comment by lduboeuf** [comment]
can't reproduce on N5 RC

**Comment by mattbel10** [comment]
Just made a call and I can confirm the mute button doesn't work at all, it's irrelevant whether you press it or not and at the other end my voice is always audible. I'm on Halium 9, devel channel, Pixel 3a.

**Comment by koenvervloesem** [comment]
I can't reproduce this on a Volla Phone, Release Candidate Channel, Ubuntu Touch version 29.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/171

Sorry for your inconvenience.
