### ISSUE TITLE
dialpad contact search: contacts with accent not retrieved 

### ISSUE THREAD

**Issue by lduboeuf** [ubports/dialer-app#177]
Create a contact: e.g ”àdel”, try to search with 233:. àdel not found

**Comment by lduboeuf** [comment]
humm it used to work, but that was before new backend preparation. 
EDIT: I remember that searching for Name and FirstName will not make search with accent working, for galera it will only work on DisplayLabel

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/175

Sorry for your inconvenience.
