### ISSUE TITLE
Favorite not possible

### ISSUE THREAD

**Issue by lduboeuf** [ubports/dialer-app#178]
on Stable OTA-21
Favorite icon does not reflect the model. A favorite contact have a transparent star icon instead of a filled one.

Should be fixed with:
https://gitlab.com/ubports/core/address-book-app/-/merge_requests/200

**Comment by lduboeuf** [comment]
fixed with the new backend

**Comment by lduboeuf** [comment]
since new backend is reverted, this bug still persist

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/176

Sorry for your inconvenience.
