### ISSUE TITLE
Speed dial

### ISSUE THREAD

**Issue by Amolith** [ubports/dialer-app#31]
I would love to see a speed dial feature! Users could possibly swipe up from the bottom and see speed dial by default with recent conversations in, say, another tab!

**Comment by bhdouglass** [comment]
I'll second this request. It's to many taps to do: contacts -> favorites -> contact -> phone call button -> dial button

**Comment by ghost** [comment]
I totally agree!

For example, we could imagine swiping up from the bottom of the screen to open the "Recent" screen, with the "All" and the "Missed" tabs.

Then in "All", by swiping on the left on a number, add a star icon after the "Info", "Message" and "Contact" icons to put in the number in the favorites (the star is then filled in grey and it is possible to remove the number from the favorites by reselecting the star). Note : it would be more robust than using the favorites in the Contacts app, as multiple phone numbers may exist for the same people. And you can also blacklist people the same way.

Finally in the "Recent" screen, a new "Favorites" tab now appears in **first** position before the "All" and the "Missed" tabs (to speed-dial). We could also imagine to pin the name of the favorites in the launcher icon for a quick access.

To go further, we could also think about reversing the "Recent" screen with the "Dialer" screen to see the "Recent" screen when opening the app an the "Dialer" screen with a swipe up, as saved numbers are used in the majority of the time instead of manual ones. This would save one swipe up (open the app, tap on a favorite and boom!).

Let me know if this makes sense.

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/17686836/43687749-2e791616-98db-11e8-9c5a-eed89233cac0.png)
![2](https://user-images.githubusercontent.com/17686836/43687750-2ec22a7c-98db-11e8-9cee-aeb033185bc0.png)
![3](https://user-images.githubusercontent.com/17686836/43687751-2efea9a2-98db-11e8-9234-380194b815f7.png)
![4](https://user-images.githubusercontent.com/17686836/43687752-2f3221ec-98db-11e8-968c-9daa00ee65fa.png)
![5](https://user-images.githubusercontent.com/17686836/43687753-2f6609e4-98db-11e8-86bc-4503eb4742cd.png)
![6](https://user-images.githubusercontent.com/17686836/43687754-2f98db12-98db-11e8-9a4b-680f21a65bb9.png)

**Comment by sbirmi** [comment]
I have a simpler proposition for implementing speed dial. Type in the number you want to program and drag and drop on one of the programmable numbers (2 thru 0). To erase, you can drag and drop the empty field (no digits typed in).

This should provide the basic functionality we want.

Nice to have add on: the "Settings" window has a "Speed dial" option that lists all numbers that are programmed (and allows you to delete the programmed numbers if needed).

**Comment by sbirmi** [comment]
Another simpler UI approach (I have the basic functionality working) is to simply type the number that needs to be saved and hold the programmable number to save.

If one of the programmable numbers is held down when there are no digits typed already, that retrieves the previously programmed numbers.

A new tab/window/widget shows all programmed numbers under 'Settings'. They can also be unprogrammed there.

**Comment by cibersheep** [comment]
Favorite contacts could be on top of the BottomEdge for Recent calls showing Picture or name initials:

![imatge](https://user-images.githubusercontent.com/6640041/60928613-67bd9e00-a2ae-11e9-8117-f1a242555206.png)

**Comment by cibersheep** [comment]
Now that we have added favorites to the header, is this still a valid issue?

**Comment by sbirmi** [comment]
I haven't tried the favorites feature but I am fine dropping the speed dial feature.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/31

Sorry for your inconvenience.
