### ISSUE TITLE
Photos of the called

### ISSUE THREAD

**Issue by Gabriele69** [ubports/dialer-app#4]
If we can express wishes on future functions, it would be nice to be able to see (during the call) the contact photo that fills the white area above the red button

GM

**Comment by ghost** [comment]
I agree!

**Comment by lduboeuf** [comment]
isn't it already the case ? the avatar is shown

![incoming-call](https://user-images.githubusercontent.com/11663835/95554333-4a770280-0a10-11eb-8546-6cbf4162c629.png)

**Comment by ghost** [comment]
Not once you take the call, because then the dialer switch in fullscreen with only the name and some icons for action

**Comment by lduboeuf** [comment]
humm ok, so maybe someone from team UI can give use some mock up ( cc @cibersheep )

**Comment by cibersheep** [comment]
The «white space» is for the numbers to show when needed during the call, no?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/4

Sorry for your inconvenience.
