### ISSUE TITLE
Call waiting / incoming call within a call sound is too loud and persistent

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/dialer-app#58]
While in a call, if another call comes in, there is a beeping tone and a sort of notification box to accept or deny the new call.

The beeping tone is too loud and frequent and disrupts the current call. The other party can hear it, especially on speakerphone. 
There is no way to block that new call from continually disrupting the call if they call back. 

1. Ideally there would be a way to "silence" the 2nd call.
2. As a workaround either disable the tone for the 2nd call
3. OR change the tone to less frequent, and less loud, or a vibration instead

**Comment by bastos77** [comment]
Same here on the FP2

**Comment by lduboeuf** [comment]
still effective on OTA-17?

**Comment by Flohack74** [comment]
This is a very old bug. Though I think its probably still there, we did not change any loudness here. We could probably just cut down the volume of the beeping sounds

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/58

Sorry for your inconvenience.
