### ISSUE TITLE
Hangup tone volume is still louder than in call volume

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/dialer-app#59]
When hanging up the call there is a tone to indicate that the call as ended.

- The tone is louder than the in call volume.
- When using a headset, it can hurt the ears.
Related to : https://github.com/ubports/dialer-app/issues/20
- It my opinion it's still too loud, and not a nice sound either.

**Comment by bastos77** [comment]
On my FP2 this is if the other party hangs up first

**Comment by dieharddan** [comment]
This happens to me as well on a opo, it's almost as if it switches to speakerphone, it's very loud

**Comment by Flohack74** [comment]
That should be fixed by now, please recheck.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/59

Sorry for your inconvenience.
