### ISSUE TITLE
sometimes hangup not possible

### ISSUE THREAD

**Issue by bastos77** [ubports/dialer-app#63]
On my FP2, at least since the upgrade to 16.04, hangup is sometimes not possible.
Once the other party picks up the call, it is not possible to hang up. Red dialer buton is visible and responsive but nothing happens.
In most cases this bug happens when an answering machine picks up.

**Comment by cyberpunkedu** [comment]
Same on Nexus 5

**Comment by dieharddan** [comment]
same issue on oneplus one

**Comment by Thieb67k** [comment]
Nexus 4: ditto.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/63

Sorry for your inconvenience.
