### ISSUE TITLE
Dialer - Podbird - Sound System Interaction is buggy

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/dialer-app#70]
device: mako
channel: 16.04/devel
build: 2019-05-17

**Note:** 
* This might be a podbird issue, or a sound module issue...
* Audio is designed to stop playing when a call is incoming or in progress. Audio resumes once call is ended. However, there is a problem as described below.

**Steps to reproduce:**
1. Play audio in Podbird
2. Get on a call
3. Another call comes in during current call
4. Dismiss incoming call

**What happens:**
* 1st call continues
* Podbird audio starts playing again while in call

**Expected**
* Audio should remain paused until all call events have ended.

**Comment by lduboeuf** [comment]
@userj , still an issue ?. 
I guess it happens not only with podbird

**Comment by cibersheep** [comment]
I can't reproduce with latest Dev on Arale

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/70

Sorry for your inconvenience.
