### ISSUE TITLE
Letter on Dial Pad Needed?

### ISSUE THREAD

**Issue by cibersheep** [ubports/dialer-app#77]
Are the letters on the dial pad needed?
If tap and hold they are doing nothing (except for the 0 and 1)

**Comment by Flohack74** [comment]
Well you know, the letters are for "vanity numbers" in USA and maybe other countries:

DIAL 555-PIZZANOW to get delicious pizza. Then when you dial this, you press the number corresponding to the letter, but you take a short press, since it is supposed to dial numbers only. The number you would dial becomes then:

555-74992669

So yes, the letters should be there, but no, they will not have any longpress effect, only decorators ;)

see also [https://en.wikipedia.org/wiki/Vanity_number](https://en.wikipedia.org/wiki/Vanity_number)
